In [7]:
import pandas as pd
pd.set_option('display.max_columns', 500)

In [9]:
df = pd.read_csv('Basketball/Box_Scores.csv', compression = 'gzip', encoding = 'latin1')
df_pbp = pd.read_csv('Basketball/Play_by_Play_data.csv', compression = 'gzip', encoding = 'latin1')

In [8]:
df.head()

,Game_id,Person_id,Team_id,First_Name,Last_Name,minutes,Field_Goals,Field_Goals_Attempted,Field_Goal_Percentage,Three_Pointers,Three_Pointers_Attempted,Three_Point_Percentage,Free_Throws,Free_Throws_Attempted,Free_Throw_Percentage,Offensive_Rebounds,Defensive_Rebounds,Assists,Personal_Fouls,Steals,Turnovers,Blocked_Shots,Points,location,outcome,season_id,vs_team_id,league_id,Technical_Fouls,Flagrant_Fouls,Ejections,Points_In_Paint,Fast_Break_Points,Triple_Doubles,Double_Doubles,actual_minutes,actual_seconds,Plus_Minus,Blocks_Against,PTS_OFF_TO,Second_Chance_PTS,Total_Rebounds
0,20300001,224,1610612748,Eddie,Jones,39,5,15,0.333,1,5,0.2,4,4,1.000,2,6,0,3,0,1,0,15,A,L,2003,1610612755,0,0.0,0.0,0.0,4.0,0.0,0.0,0.0,39,0,-7,0.0,2,2,8.0
1,20300001,243,1610612755,Aaron,McKie,24,3,7,0.429,2,2,1.0,2,2,1.000,0,4,1,3,1,1,0,10,H,W,2003,1610612748,0,0.0,0.0,0.0,0.0,2.0,0.0,0.0,24,0,15,0.0,5,3,4.0
2,20300001,258,1610612748,Brian,Grant,29,4,5,0.800,0,0,0.0,5,6,0.833,2,5,0,3,0,5,0,13,A,L,2003,1610612755,0,0.0,0.0,0.0,6.0,0.0,0.0,0.0,29,0,-11,1.0,0,4,7.0
3,20300001,727,1610612755,Eric,Snow,31,0,5,0.000,0,1,0.0,1,2,0.500,2,2,6,2,1,1,0,1,H,W,2003,1610612748,0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,31,0,11,1.0,1,0,4.0
4,20300001,902,1610612748,Vernell,Coles,5,0,0,0.000,0,0,0.0,0,0,0.000,0,0,0,0,0,0,0,0,A,L,2003,1610612755,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,5,0,-4,0.0,0,0,0.0

In [5]:
df.shape

(428463, 42)

In [16]:
df_pbp.head()

,Game_id,Event_Num,Event_Msg_Type,Description,Period,WC_Time,PC_Time,SC_Time,Play_Loc_sd,Play_Loc_fd,Action_Type,Option1,Option2,Team_id,Person1,Person2,Person3,Team_id_type
0,20300001,0,12,(12:00) Start Period,1,549198,7200,-1.0,0,0,0,0,0,0,0,0,0,0
1,20300001,1,10,(12:00) Jump Ball Thomas vs Grant,1,549259,7200,-1.0,0,0,0,0,0,0,1903,258,2617,0
2,20300001,2,2,(11:48) [MIA] Wade Layup Shot: Missed,1,549469,7080,24.0,0,0,5,2,0,1610612748,2548,0,0,3
3,20300001,3,4,(11:46) [PHL] Thomas Rebound (Off: Def:1),1,549484,7060,23.0,0,0,0,0,0,1610612748,1903,0,0,3
4,20300001,5,1,(11:21) [PHL 3-] Salmons Jump Shot: Made (3 PT...,1,549732,6810,24.0,-233,43,1,3,0,1610612755,2422,727,0,2

In [15]:
df_pbp.shape

(9873240, 18)